# Exercise 1
Import the NUMPY package under the name np.

In [1]:
import numpy as np

# Exercise 2
Print the NUMPY version and the configuration.

In [2]:
print('Numpy version:', np.__version__)
print('Numpy configuration:', np.show_config())

Numpy version: 1.24.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros 

# Exercise 3
Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1: Using np.random.random to generate random values between 0 and 1
a = np.random.random((2,3,5))

# Method 2: Using np.random.rand to generate random values between 0 and 1
a2 = np.random.rand(2,3,5)

# Method 3: Using np.random.randn to generate random values from a standard normal distribution
a3 = np.random.randn(2,3,5)

# Method 4: Using np.random.randint to generate random integers (example: between 0 and 10)
a4 = np.random.randint(0, 10, (2,3,5))

# Method 5: Using np.random.uniform to generate random floats in a specific range (example: between 0 and 5)
a5 = np.random.uniform(0, 5, (2,3,5))


# Exercise 4
Print a.

In [4]:
print('a:', a)

a: [[[0.29485645 0.48396231 0.81449444 0.84515042 0.00770593]
  [0.33179939 0.20138757 0.2024915  0.46472928 0.12452575]
  [0.62630023 0.83674553 0.03856966 0.46828623 0.21553106]]

 [[0.07156424 0.35699198 0.47138783 0.22243115 0.09188623]
  [0.26824746 0.66983234 0.51901898 0.48640224 0.47413598]
  [0.89664816 0.21372797 0.8071379  0.85085318 0.38207381]]]


# Exercise 5
Create a 5x2x3 3-dimensional array with all values equaling 1.
Assign the array to variable "b"

In [5]:
b = np.ones((5,2,3))

# Exercise 6
Print b.

In [6]:
print('b:', b)

b: [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# Exercise 7
Do a and b have the same size? How do you prove that in Python code?

In [7]:
print('a size:', a.size)
print('b size:', b.size)
print('a size == b size:', a.size == b.size)
# Yes, a and b have the same size because they both have 30 elements.

a size: 30
b size: 30
a size == b size: True


# Exercise 8
Are you able to add a and b? Why or why not?

In [8]:
try:
    print(a + b)
except Exception as e:
    print('Error:', e)
# No, because the two arrays have different shapes.

Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


# Exercise 9
Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to variable "c".

In [9]:
c = np.transpose(b, (1,2,0))

# Exercise 10
Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?

In [10]:
d = a + c
# Now it works because the two arrays have the same shape.

# Exercise 11
Print a and d. Notice the difference and relation of the two arrays in terms of the values? Explain.

In [11]:
print('a:', a)
print('d:', d)
# The values in d are the same as the values in a plus 1. This is because we added the array c to a, and c is an array of ones.

a: [[[0.29485645 0.48396231 0.81449444 0.84515042 0.00770593]
  [0.33179939 0.20138757 0.2024915  0.46472928 0.12452575]
  [0.62630023 0.83674553 0.03856966 0.46828623 0.21553106]]

 [[0.07156424 0.35699198 0.47138783 0.22243115 0.09188623]
  [0.26824746 0.66983234 0.51901898 0.48640224 0.47413598]
  [0.89664816 0.21372797 0.8071379  0.85085318 0.38207381]]]
d: [[[1.29485645 1.48396231 1.81449444 1.84515042 1.00770593]
  [1.33179939 1.20138757 1.2024915  1.46472928 1.12452575]
  [1.62630023 1.83674553 1.03856966 1.46828623 1.21553106]]

 [[1.07156424 1.35699198 1.47138783 1.22243115 1.09188623]
  [1.26824746 1.66983234 1.51901898 1.48640224 1.47413598]
  [1.89664816 1.21372797 1.8071379  1.85085318 1.38207381]]]


# Exercise 12
Multiply a and c. Assign the result to e.

In [12]:
e = a * c

# Exercise 13
Does e equal to a? Why or why not?

In [13]:
print('e == a:', np.array_equal(e, a))
# Yes, because we multiplied each element in a by 1 (the corresponding element in c), so the values in e are the same as in a.

e == a: True


# Exercise 14
Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [14]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print('d_max:', d_max)
print('d_min:', d_min)
print('d_mean:', d_mean)

d_max: 1.8966481609903685
d_min: 1.0077059285844094
d_mean: 1.4246291740009793


# Exercise 15
Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [15]:
f = np.empty((2,3,5))

# Exercise 16
Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.

Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.

Note: you don't have to use Numpy in this question.

In [16]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100

# Exercise 17
Print d and f. Do you have your expected f?

For instance, if your d is:
```python
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
```
Your f should be:
```python
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],
       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
```

In [17]:
print('d:', d)
print('f:', f)

d: [[[1.29485645 1.48396231 1.81449444 1.84515042 1.00770593]
  [1.33179939 1.20138757 1.2024915  1.46472928 1.12452575]
  [1.62630023 1.83674553 1.03856966 1.46828623 1.21553106]]

 [[1.07156424 1.35699198 1.47138783 1.22243115 1.09188623]
  [1.26824746 1.66983234 1.51901898 1.48640224 1.47413598]
  [1.89664816 1.21372797 1.8071379  1.85085318 1.38207381]]]
f: [[[ 25.  75.  75.  75.   0.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  75.  25.  75.  25.]]

 [[ 25.  25.  75.  25.  25.]
  [ 25.  75.  75.  75.  75.]
  [100.  25.  75.  75.  25.]]]


# Exercise 18 - Bonus question
Instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values ("A", "B", "C", "D", and "E") to label the array elements?

You are expecting the result to be:
```python
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],
       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
```
Again, you don't need Numpy in this question.

In [18]:
f = f.astype(str)
f[f == '0.0'] = 'A'
f[f == '25.0'] = 'B'
f[f == '50.0'] = 'C'
f[f == '75.0'] = 'D'
f[f == '100.0'] = 'E'
print('f:', f)

f: [[['B' 'D' 'D' 'D' 'A']
  ['B' 'B' 'B' 'D' 'B']
  ['D' 'D' 'B' 'D' 'B']]

 [['B' 'B' 'D' 'B' 'B']
  ['B' 'D' 'D' 'D' 'D']
  ['E' 'B' 'D' 'D' 'B']]]
